### ISSUE TITLE
Migrate magpie to LLNL organization

### ISSUE THREAD

**Issue by IanLee1521** [LLNL/magpie#103]
This issue is for moving the magpie repository under the [LLNL](https://github.com/llnl) organization rather than having it under chu11. Issues and Pull requests will migrate if done through the GitHub ["Transfer Ownership"](https://help.github.com/articles/transferring-a-repository/) process.

**Comment by chu11** [comment]
As discussed, will be migrated in the not-so-distant future.

**Comment by chu11** [comment]
done
