### ISSUE TITLE
Allow overriding individual settings

### ISSUE THREAD

**Issue by joshuata** [LLNL/magpie#149]
Currently there is no way to override a single configuration file (such as log4j properties) without copying the entire set of configuration files for an application. It would be helpful if the user could specify a conf directory that would be checked for user-specific files, but would fall back to the default if it was not found.

For example, in magpie-setup-spark:
```sh
defaultsparkconffiledir=${MAGPIE_SCRIPTS_HOME}/conf

if [ "${SPARK_CONF_FILES}X" == "X" ]
then
    pre_sparkenvsh=${sparkconffiledir}/spark-env-0.X.sh
    pre_log4jproperties=${sparkconffiledir}/spark.log4j-0.X.properties
else
    if [ -f "${SPARK_CONF_FILES}/spark-env-1.X.sh" ]
    then
        pre_sparkenvsh=${SPARK_CONF_FILES}/spark-env-1.X.sh
    else
        pre_sparkenvsh=${defaultsparkconffiledir}/spark-env-1.X.sh
    fi
# Set other variables
fi
```

**Comment by chu11** [comment]
In hindsight, that seems like a super obvious thing to do :-)  This was likely a byproduct of all those hacked up scripts I started with long ago.

**Comment by chu11** [comment]
Will be in 1.73
