### ISSUE TITLE
Add Zeppelin core tests to Testuite

### ISSUE THREAD

**Issue by chu11** [LLNL/magpie#198]
Related to #196, could make #196 not an issue

**Comment by chu11** [comment]
Tests based on Spark w Standalone and Spark w/ Yarn

**Comment by joshuata** [comment]
Alright, you should be able to assign this task to me now

**Comment by joshuata** [comment]
I think our best bet for testing sanity is using the [rest api](http://zeppelin.apache.org/docs/0.6.0/rest-api/rest-configuration.html). A simple request can verify that the server has started. Unfortunately I'm not sure how to make this happen with the security measures (ip-isolation) that we have.

**Comment by chu11** [comment]
How about launching a generic script that does wget or whatever (or it could be a small python script) that is launched via MAGPIE_JOB_TYPE="script".  Because that script that is run is already inside the allocation, it should be able to get to the Zeppelin no problem.

**Comment by joshuata** [comment]
Due to the way zeppelin is setup we need to specify the `ZEPPELIN_HOME` variable, which is different for each version. Is there a default format I should use, or a correct place to expect these files?

**Comment by chu11** [comment]
ZEPPELIN_HOME should be exported when magpie runs the script.  It should be carried through all the way from when it was specified in the job submission script.  As an example, you'll see in:

testsuite/testscripts/test-hadoopterasort.sh 

you'll see I cd into HADOOP_HOME before calling various Hadoop things.  Likewise with many of the other scripts in there.

If ZEPPELIN_HOME isn't specified, that's a bug we should look into.

Out of my curiosity, what do you need to get out of ZEPPELIN_HOME?  If it's important, perhaps it'd be better for us to have magpie export that into a new environment variable for scripts to use.  As an example, I created the ZOOKEEPER_NODES_FIRST environment variable for Zookeeper to export.  Some random software wanted a node in the Zookeeper allocation.  Rather than having user scripts figure out what node was the right zookeeper node to use, I had Magpie just export this so it was easier.

**Comment by joshuata** [comment]
I'm just unsure where I should get the value from in order to set it in the submission script.
I assume it will be something similar to the LC clusters where there is a directory `***/zeppelin_${version_number}` for each version we installed.

**Comment by chu11** [comment]
I just saw your pull request, I think I know what you're talking about now.  You're talking about the fact the directories are

zeppelin-0.5.6-incubating-bin-all
vs.
zeppelin-0.6.0-bin-all

I think it'll work out if we use ZEPPELIN_VERSION="0.5.6-incubating" instead.  That was probably the mistake.  I'll discuss this more in the pull request.

**Comment by chu11** [comment]
Or I now realize .... you just might be talking about something far more generic, in that there is no way to set the zeppelin path in testsuite/test-config.sh?  I should emulate all of the configs that are in submission-scripts/script-templates/Makefile.

**Comment by chu11** [comment]
renaming to indicate these are the "core" tests, new issue to be opened for corner case tests and what not
