### ISSUE TITLE
update/fix how ZEPPELIN_VERSION is used

### ISSUE THREAD

**Issue by chu11** [LLNL/magpie#206]
ZEPPELIN_VERSION should be "0.5.6-incubating", not "0.5.6", fallout is how ZEPPELIN_HOME is used and the names of jars that are used, and testsuite too

**Comment by chu11** [comment]
in 'zeppelinfixes' branch

**Comment by joshuata** [comment]
I noticed you did not change the reference in `magpie/setup/magpie-setup-project-spark:490`. Was this missed, or is there a reason to leave that reference.

Also, there is zeppelin setup work done in `magpie-setup-project-spark` as well as `magpie-setup-project-zeppelin`. Should we consolidate this into a single location?

**Comment by chu11** [comment]
Nope, completely missed `magpie/setup/magpie-setup-project-spark:490`, that's why we need this test suite.  Wanna send me pull request or should I fix?

**Comment by chu11** [comment]
As for common setup work, I don't quite see the similarities in the setup work at the moment, but that doesn't mean it isn't there.  If you think some common code in `magpie/lib/magpie-lib-setup` or similar is warranted, go for it.

**Comment by joshuata** [comment]
I can take care of the version problem.

**Comment by chu11** [comment]
cool, thanks

**Comment by joshuata** [comment]
Fixed in #213
