### ISSUE TITLE
support zeppelin "test zeppelin" mode option

### ISSUE THREAD

**Issue by chu11** [LLNL/magpie#207]
to sanity test that zeppelin is working, name can be adjusted (ping zeppelin? call zeppelin? check zeppelin up?)
per discussion on #198, a simple call to the REST interface should be sufficient

remember to document dependencies if it uses wget, python, or whatever

also should be added into 'testall'

**Comment by chu11** [comment]
related to #198 , assigning to josh

**Comment by joshuata** [comment]
What is the purpose of the `Generate${project}PostProcessing` functions? I see that they make modifications to some files, but I can't tell what their exact purpose is.

**Comment by chu11** [comment]
Many of the PostProcessings are to set the filenames for the output files being generated.  For example, set the filename to _slurm-run-hadoopterasort-%j.out_ for terasort tests.  The information in the filename is subsequently used by `test-validate.sh` to determine how it the output should be validated.

Others are for setting run parameters in the submission scripts.  For example, minutes the job has to complete (e.g. hbase tests get more time than storm tests).

I admit it's not the most intuitive.  Partly the outcome of what was once a simple testsuite with just 10 submissions scripts doing some basic tests.

Hmmm, it might a good intern project to sort of remake the testsuite now that it's so much more substantial.  Generate a "data file" of all the permutations of tests you want to do, submission scripts get generated off the "data file", and test validation also off the "data file".  I'll add it to the list of potential projects :-)

**Comment by chu11** [comment]
ended up being called 'checkzeppelinup'
