### ISSUE TITLE
PHOENIX_START_QUERYSERVER doesn't do anything

### ISSUE THREAD

**Issue by bpanneton** [LLNL/magpie#226]
There is an option in the Phoenix setup that doesn't do anything. 

```
export PHOENIX_START_QUERYSERVER="yes"

# Set phoenix job for MAGPIE_JOB_TYPE = phoenix
#
# "performanceeval" - run performance evaluation write and read.
#              Useful for making sure things are setup the way you
#              like.
#
# "script" - execute a phoenix script indicated by PHOENIX_SCRIPT_PATH.
#            Unlike "script" in MAGPIE_JOB_TYPE, this script is
#            executed via the 'sqline.py' command.
#
```

I think we should  use the option which makes sense, however it needs to be implemented in the code. Also the MODE should include interactive. (server is still implemented in the code)

This was likely due to this discussion:
https://github.com/LLNL/magpie/issues/100

I wanted to check you didn't already have plans for something before I cleaned this up.

**Comment by bpanneton** [comment]
Kafka is this way as well except it seems like anything other than setuponly will start the service. Perhaps we should add interactive here as well.

**Comment by bpanneton** [comment]
And Zeppelin. With Kafka and Zeppelin maybe its just a documentation change.

**Comment by bpanneton** [comment]
And ZooKeeper

**Comment by chu11** [comment]
For magpie 2.0, "interactive" is now only configurable in the "MAGPIE_JOB_TYPE" config at the top of the file.  Basically, it was a waste to have "interactive" and "script" modes through all of the "MODE" variables (which are now "JOB" variables) even though they almost all did the same thing.

Does that clarify things?

**Comment by bpanneton** [comment]
Okay, it must have carried over to pre 2.0. Some, like zookeepr don't have the interactive option and use launch. I'll let this one be for now.

**Comment by chu11** [comment]
Some projects like Zookeeper never had an interactive mode b/c it sort of didn't make sense for them.
