### ISSUE TITLE
Allow user to set SPARK_LOG_DIR path

### ISSUE THREAD

**Issue by akthoma** [LLNL/magpie#236]
Hello,

I am trying to run magpie with spark via slurm. $SPARK_HOME is located in an unwritable directory, and log files keep being attempted to be written to that directory. I would like to be able to have log files to be written to the user's working directory (or wherever their preference is), but I cannot seem to find a way to make this work. 

I have tried setting the desired SPARK_LOG_DIR path in my run script, conf/spark/spark-env.sh, and conf/spark/spark-env-1.X.sh, and still get the same result of spark trying to write a log file to a directory where the permission is denied (SPARK_HOME). 

When I am running spark on its own without magpie, the logs go where I want them to when I set the variable in the spark-env.sh script within spark's own config directory.

I am using spark 2.1.0 and magpie 1.81

Any help would be very appreciated. Thank you!

**Comment by chu11** [comment]
Hmm, I'm not sure what is different about your setup that would not make this work.  I'm wondering if the config files for SPARK_CONF_DIR are being loaded correctly, thus SPARK_LOG_DIR is not being pointed to correctly.

Have you applied the patch "spark-2.1.0-bin-hadoop2.7-alternate.patch" from Magpie to your Spark installation?

**Comment by akthoma** [comment]
@chu11 Thank you for your suggestion! I applied the patch that you mentioned above, but still had no luck. I did get it to work though, by changing line 250 in magpie/magpie/exports/magpie-exports-dirs to my desired output directory. Other than the submission script, that change was the only one that I made to the magpie directory.

**Comment by chu11** [comment]
Hmmm.  Wonder what the issue could have been.  I suspect the environment your slurm is setup in is slightly different than mine (perhaps some missing environment variable or something), thus something gets set up somewhat differently.
