### ISSUE TITLE
Add support for Spark 2.2.0

### ISSUE THREAD

**Issue by lazariv** [LLNL/magpie#239]
Thank you for developing such a great and useful scripts!

I am running Spark on a cluster with Slurm scheduling. After upgrading from Spark version 2.1.0 (which worked great) to 2.2.0 I am getting the following error
```
Exception in thread "main" java.lang.UnsupportedClassVersionError: JVMCFRE003 bad major version; class=org/apache/spark/launcher/Main, offset=6
	at java.lang.ClassLoader.defineClassImpl(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:331)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:155)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:714)
	at java.net.URLClassLoader.access$400(URLClassLoader.java:93)
	at java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1166)
	at java.security.AccessController.doPrivileged(AccessController.java:488)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:597)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:786)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:760)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:330)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:741)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
```
in the logs of Workers and the following output in the magpie *.out file 
```
failed to launch: nice -n 0 /home/***/spark-2.2.0-bin-hadoop2.7/bin/spark-class org.apache.spark.deploy.worker.Worker --webui-port 8081 spark://***:7077
***:   	at java.lang.ClassLoader.loadClass(ClassLoader.java:741)
***:   	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
```
The major change in Spark from 2.1.0 to 2.2.0 is, that Java 7, Python 2.6 and old Hadoop versions before 2.6.5 were removed as of Spark 2.2.0.

Another comment: I figured out, that magpie uses Python 2.6, but when I supply `export MAGPIE_PYTHON`  with the Python2.7 installation folder I get empty *.out file at all. 

I would be very thankful for any clues

**Comment by chu11** [comment]
Thanks!  I tend to update Magpie with recent latest releases in batches once in awhile.  Hopefully I can get to Spark in the near future (seems it was released just 2 weeks ago).

The first error you show definitely seems like a java version error.  Did using any other java version fix the problem?

Not sure about the Python2.7 problem, are you able to run "sparkpi" or something similarly simple for starters?

**Comment by lazariv** [comment]
We have `java/jdk1.7.0_25` and `java/jdk1.8.0_66` available on the cluster. If using `java/jdk1.7.0_25`, neither the spark-master nor the spark-worker can be started. With `java/jdk1.8.0_66` at least master is up and running. But the workers are failed to start.  

I have managed to start workers manually, after logging-in to worker-node and loading at first correct java version (1.8.0). No idea why, but it seems that the `JAVA_HOME` path on the worker node is `/usr/bin/java` (which is 1.7.0) and not the one, provided in magpie.sbatch-srun-spark file
 
I am always running magpie in "testall" mode with "sparkpi" at first, to test everything.

**Comment by lazariv** [comment]
I have found the following work-around:
add additional `export JAVA_HOME=/sw/global/tools/java/jdk1.8.0_66` to the `start-slaves.sh` script, so it looks like following 
```
# Launch the slaves
"${SPARK_HOME}/sbin/slaves.sh" cd "${SPARK_HOME}" \; export JAVA_HOME=/sw/global/tools/java/jdk1.8.0_66 \; "${SPARK_HOME}/sbin/start-slave.sh" "spark://$SPARK_MASTER_HOST:$SPARK_MASTER_PORT"
```
Maybe you could check this issue and the one with python 2.7+ in future releases?

**Comment by chu11** [comment]
Just to double check, did you apply the patches from the ```patches``` directory to your spark?  I know there's not a Spark 2.2.0 patch equivalent yet, but perhaps the 2.1.1 ones will apply cleanly.

I think the unit tests right now just use whatever python is the default installed.  Perhaps in the future I can test multiple.  I'll add an issue to the TODO list.

**Comment by chu11** [comment]
Support in Magpie will not happen for atleast a bit.

https://issues.apache.org/jira/browse/SPARK-21570

**Comment by chu11** [comment]
Well, upstream seems to suggest yarn w/ non-HDFS is not supported.  So I will probably add support w/ a caveat.
