### ISSUE TITLE
Spark master and workers use different conf directories

### ISSUE THREAD

**Issue by lazariv** [LLNL/magpie#265]
Thanks a lot for your work! I face this issue when trying to use spark.authenticate feature. The problem is that the workers cannot connect to master throwing the error
`java.lang.IllegalArgumentException: Authentication failed` and `Failed to connect to master *** Exception thrown in await result`

After viewing the logs I noticed that the master process was started with 
`Spark Command:  JAVA_HOME -cp /tmp/USER/spark/test1/jobID/conf:SPARK_HOME/jars ........`  but the workers are started with `Spark Command:  JAVA_HOME -cp SPARK_HOME/conf:SPARK_HOME/jars ........` 

Therefore I suppose that the workers do not know the actual SPARKAUTHENTICATESECRET which was generated by magpie.  Do you have any ideas how to fix this?

Here are the only changes in `magpie/submission-scripts/script-sbatch-srun/magpie.sbatch-srun-spark` regarding the directories
``` 
export SPARK_LOCAL_DIR="/tmp/${USER}/SPARK"
export SPARK_LOCAL_SCRATCH_DIR="/scratch/projetc/.../sparkscratch"
```
All other options are default
  

UPDATE:
The workaround was found by specifying the same predefined `spark.authenticate.secret`  in both `SPARK_HOME/conf/spark-defaults.conf` and in `magpie/conf/spark/spark-defaults.conf` files.

**Comment by chu11** [comment]
Hi, in your spark, did you apply the ```spark-YOURVERSION-alternate.patch``` that is in ```patches/spark```?  That patch has a few minor mods to the spark launching scripts to ensure that ```/tmp/USER/spark/test1/jobID/conf``` is used as the conf dir instead of ```SPARK_HOME/conf```.

**Comment by lazariv** [comment]
Hey. Thanks, I will try it and post an update.
