### ISSUE TITLE
Trouble starting Magpie

### ISSUE THREAD

**Issue by nealepetrillo** [LLNL/magpie#277]
Howdy! 

I'm trying to run the Terasort test though Magpie with no success. When I submit the example script (after adding appropriate SBATCH directives) "magpie.sbatch-srun-hadoop" I get no meaningful output.

Adding echo statements as suggested in #275 gives me output at each step in the "magpie.sbatch-srun-hadoop" with no errors reported. I can also see the configuration files and scratch areas being crated in /tmp/ on each worker node but I don't see anything in the /lustre/ area.

The system is configured with Hadoop version 2.9 under Oracle Java 1.8 on CentOS 7. The shared areas are all Lustre 2.10 based. 

Am I missing a step somewhere? Does anybody have any suggestions? 

Thanks!

**Comment by chu11** [comment]
By "don't see anything in the /lustre" area, do you mean you don't see any data written, or don't see directories and other scratch files created?

In README.hadoop, there is an example output from a terasort.  What parts of this have you seen?  For example, have you see output indicating the Hadoop as started its appropriate daemons.

**Comment by nealepetrillo** [comment]
In /lustre there is no data or directories or scratch files.

I see nothing that corresponds to the README.hadoop file. I would at least expect to see some of the headings but nothing appears to show up in standard out. If I add echo statements to my submission script, I can see those as expected, though. Could there be some kind of problem with piping through subshells? 

I tried removing the #SRUN --ouput line as well as adding a -e file to the sbatch command with no change in behavior.

**Comment by chu11** [comment]
> Could there be some kind of problem with piping through subshells?

I suppose this could be an issue.  But my understanding is that slurm always pipes all the way back to the original sbatch/srun by default.  Have you tested your theory?  You could just add a:

```
srun --no-kill -W 0 my-echo-script.sh
```

to the sbatch file and have that script echo output as a test.

**Comment by nealepetrillo** [comment]
This works as expected.

``srun --no-kill -W 0 my-echo-script.sh

If Magpie is unable to start the Hadoop daemons, where would that error output go?

**Comment by chu11** [comment]
Those errors would just be output to stdout/stderr.

Just to make sure, you added echo statements and are sure that all the srun calls below are returning 0?  It's not exiting at any of these points?

```
srun --no-kill -W 0 $MAGPIE_SCRIPTS_HOME/magpie-check-inputs
if [ $? -ne 0 ]
then
    exit 1
fi
srun --no-kill -W 0 $MAGPIE_SCRIPTS_HOME/magpie-setup-core
if [ $? -ne 0 ]
then
    exit 1
fi
srun --no-kill -W 0 $MAGPIE_SCRIPTS_HOME/magpie-setup-projects
if [ $? -ne 0 ]
then
    exit 1
fi
srun --no-kill -W 0 $MAGPIE_SCRIPTS_HOME/magpie-setup-post
if [ $? -ne 0 ]
then
    exit 1
fi
srun --no-kill -W 0 $MAGPIE_SCRIPTS_HOME/magpie-pre-run
if [ $? -ne 0 ]
then
    exit 1
fi
```
If you're using HDFS over Lustre, then some directories/scratch should have been created in your ```/lustre``` path.

I'm wondering if there is simply some corner case path where an error occurs but I don't output an error.  Or perhaps some script that I call that due to a corner case path isn't outputting an error and thus you get no output.

**Comment by chu11** [comment]
Looks like there's just some weird corner case that's being missed and we'll have to get debug this one down.

1) Could you try adding some echo debuggings into ```magpie-setup-project```, to make sure the hadoop setup is being called.  I'm a tad concerned that extra directories and some scratch stuff hasn't been generated in your lustre path.

2) Likewise in ```magpie-setup-post```.

3) Try adding some echo debugging into ```magpie-run``` around anything that says hadoop.  Also, try adding some debuggings around the "am I master" code at the beginning of the script.

**Comment by nealepetrillo** [comment]
Following debug lines to the magpie-setup-projects script got me to:

if ! Magpie_am_I_a_hadoop_node
then
    exit 0
fi

It never got past this check. Looking into the Magpie_am_I_a_hadoop_node function, it looks like the it checks the hostname of the node and compares it to some configuration file. Can you tell me where that conf file is? Maybe the hostnames are getting mangled or mismatched somewhere...

**Comment by chu11** [comment]
In your /tmp directory where Magpie is creating conf files, there should be a file called ```master``` and ```slaves```.  What do those files look like?

I'm wondering if your nodes are named/numbered in a unique way that the hostlist expansion code doesn't understand it.

**Comment by nealepetrillo** [comment]
Taking a look at what should be the master node, I see: '/tmp/<username>hadoop/' and '/tmp/<username>/magpie'

Drilling down into '/tmp/<username>/hadoop/hadoop_test/<job number>/conf/' I see three files: 'masters', 'slaves', 'slaves_fqdn' which appear to have the appropriate short names / fqdns for my nodes. All the nodes have names like bi01, bi02, etc. so no dashes or anything weird like that.  

I should mention that SLURM is configured with short names for all the nodes. I'm not sure if that makes a difference or not.

**Comment by nealepetrillo** [comment]
Okay, changing the `hostname` call to `hostname -s` seemed to fix the issue. At least the Hadoop services start up and it appears to run terasort but it hangs on shutdown for some reason. 

I also noticed that there were some errors in the `slurm.out` file:

`setstripe: unrecognized optino '--count'`

What version of Lustre are you guys testing against? The 2.11 LFS commands require: 

`lfs setstripe --stripe-count `

**Comment by chu11** [comment]
Ok.  I'll have to think about how to handle this issue in the future.  The most minimal thing that can be done is to try and add some error checks of some kind.  I've made an issue for this todo later.

As for your Lustre issue, I've recently been testing against 2.8.  It appears that ```--count``` is legacy and ```--stripe-count``` is already supported in many older versions.  So we can tweak that.  Would you like to send a PR, or I can just put it on my TODO list to do later.

**Comment by nealepetrillo** [comment]
I'll send in a PR to migrate `--count` to `--setstripe` and a TODO is fine for the hostname issue; I think I'm a corner case in that regard.

**Comment by chu11** [comment]
So for anyone that may see this issue in the future, with future version of Magpie, the new MAGPIE_HOSTNAME_CMD_MAP and MAGPIE_HOSTNAME_SCHEDULER_MAP options may be able to solve this.

https://github.com/LLNL/magpie/commit/1f821d43d28ef69e175c185609e48f51060ee43b
