### ISSUE TITLE
ray should honor MAGPIE_HOSTNAME_SCHEDULER_MAP

### ISSUE THREAD

**Issue by chu11** [LLNL/magpie#314]
initial experimentation implementations do not

**Comment by Kmannth** [comment]
I can run the TensorFlow+Horovod based jobs **without** setting 
"
export MAGPIE_HOSTNAME_SCHEDULER_MAP="${MAGPIE_SCRIPTS_HOME}/scripts/hostname-map-scripts/map-script.sh"
"
like I have to for Spark jobs. 

What would MAGPIE_HOSTNAME_SCHEDULER_MAP  do for the MPI based TensorFlow jobs?

**Comment by chu11** [comment]
Now that you mention it, it actually wouldn't affect tensorflow, since tensorflow does not care about the hostnames the scheduler uses.  It would affect ray though.  Sorry if I scared you :P
