### ISSUE TITLE
Problem when testing the "TeraSort" example

### ISSUE THREAD

**Issue by YaweiZhao** [LLNL/magpie#96]
I am a PhD student and want to do data analysis on the supercomputers such as *Tianhe-1* and *Tianhe-2*. So I have deployed **Magpie** on both of two supercomputers. After the deployment is completed, we test **Magpie** by using the given examples by **Hadoop** such as **TeraGen**, **TeraSort**, **PI** and **WordCount**.

However, it does not work very well all the time. On one hand, it works well for the **TeraGen**, **PI** and **WordCount** applications. On the other hand, it can not work for the **TeraSort** application at all. The error information which is printed to the console of the master node is presented as below:
![image](https://cloud.githubusercontent.com/assets/16436657/12059414/a8fa4c98-af95-11e5-9c6d-83e2d7d65717.png)

Then I scan the log file of the slave node, i.e., **cn1268**, and find:
![image](https://cloud.githubusercontent.com/assets/16436657/12059424/d9dbedee-af95-11e5-81cf-d1a48e4348f6.png)

I try to shut down all the **Hadoop** daemons, and re-start it. However, the problem still exists. Besides, I re-compile the **TeraSort** program and find no problems on the master node, i.e., resource manager (I add many diagnose information and print them on the console of master node.). 

p.s. 
* Both *Tianhe-1* and *Tianhe-2* computers use **Lustre** file system. I use **Lustre** file system instead of **HDFS** when deploying **Hadoop** via **Magpie**.
* The operating system deployed on the compute nodes is the clipped RedHat 6.2. Many basic tools such as *getconf* are not included in such operating system. (I have installed such tools now.)

I wonder why the applications like **WordCount**, **PI** and **TeraGen** can run successfully, but **TeraSort** fails. Would it be possible to help us find the bug, and improve **Magpie** together?

**Comment by chu11** [comment]
Typically a bind exception occurs b/c another copy of the daemon (in this case the Yarn daemon) is already running.  I'd make sure that the daemon has been killed across all nodes before launching a job.  The daemon may have been left running if a prior job was killed incorrectly & the resource manager did not kill the daemon correctly.

**Comment by YaweiZhao** [comment]
I ran **teragen** and **terasort** by hand, instead of using the batch script. Since I login in Tianhe-1 and allocate new computer nodes to perform **teragen** and **terasort** every time, there are no existing active Yarn daemons before I perform **terasort**. Besides, I notice some information below in the file "*magpie.sbatch-srun*":
![capture](https://cloud.githubusercontent.com/assets/16436657/12141095/a5906440-b4a7-11e5-95c9-64451ad87d08.PNG)
Since Tianhe-1 supercomputer does not have local storage, is it not appropriate to install **Hadoop** over **rawnetworkfs** instead of **HDFS** over **Lustre**? Do you think that this might cause the bug?

**Comment by chu11** [comment]
First try and use the Magpie terasort test by setting HADOOP_MODE to "terasort".  If that works, then there may be errors with how you are running it by hand.

I would recommend running with HDFS over Lustre first instead of rawnetworkfs.  There is a known bug in terasort when running with rawnetworkfs.  See https://issues.apache.org/jira/browse/MAPREDUCE-5528

**Comment by YaweiZhao** [comment]
I try to run **terasort** on HPC clusters by using the batch script in **Magpie**. However, I find that the namenode always fails to exit safe mode. The log file is attached.
[slurm-1036890.txt](https://github.com/chu11/magpie/files/80820/slurm-1036890.txt)

![capture](https://cloud.githubusercontent.com/assets/16436657/12165219/04821836-b557-11e5-8088-a1b0d5b0195d.PNG)

Besides, something below confuses me.
![capture](https://cloud.githubusercontent.com/assets/16436657/12165088/dc8aa920-b555-11e5-8d51-203e7029992b.PNG)
I remember that reducers cannot be started if maps do not finished. So I specify the value of  HADOOP_MAPREDUCE_SLOWSTART 0.99. Do I misunderstand something?

**Comment by chu11** [comment]
What errors are you seeing in the HDFS namenode master log file?  That will explain why the name is failing to exit safe mode.

You do not need to change HADOOP_MAPREDUCE_SLOWSTART, that is an advanced tuning parameter.  See the Hadoop configuration mapreduce.job.reduce.slowstart.completedmaps if you want to read about the nitty gritty details on what it means.

**Comment by YaweiZhao** [comment]
The error in the HDFS namenode master log file is presented as below:
in file "hadoop-kd_yjp-secondarynamenode-cn872.log">>
![capture11](https://cloud.githubusercontent.com/assets/16436657/12188148/7c73894c-b5ed-11e5-82f6-0031ac8ae635.PNG) 
in file "yarn-kd_yjp-resourcemanager-cn872.log">>
![capture10](https://cloud.githubusercontent.com/assets/16436657/12188162/a7f91ce4-b5ed-11e5-97a4-91f552140b36.PNG) 
Then, I change the value of variable "fs.defaultFS" in the file "magpie/conf/core-site-2.0.xml" as the error prompts. Its value is "hdfs://hdfs/".
![capture12](https://cloud.githubusercontent.com/assets/16436657/12188284/adf30e24-b5ee-11e5-9bd3-4dc6388c51d6.PNG)

Such an error disappears. However, the namenode master still cannot exit safemode. I find no errors in the log file.

Besides, I try to run wordcount, but there is a bug:
![image](https://cloud.githubusercontent.com/assets/16436657/12188527/2a559d4a-b5f1-11e5-8a75-caee59af6377.png)

It seems that hdfs is not configured correctly.

**Comment by bpanneton** [comment]
This might not be the issue, as I am not familiar with Lustre, however, have you tried setting MAGPIE_NO_LOCAL_DIR="yes"? If so make sure that the configuration directories that are listed in the log actually can be accessed from the node. The HPC system I use does not have local storage and I use HADOOP_FILESYSTEM_MODE="hdfsovernetworkfs". Perhaps you can post your job script as well.

**Comment by chu11** [comment]
dropping issue, i'm assuming solved by now
